insert into refusal(element, lambda, unit) VALUES ('Микросхемы интегральные полупроводниковые цифровые', '0.1968e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Оперативные запаминающие устройства(ОЗУ)', '0.1388e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Постоянные запаминающие устройства(ПЗУ)', '0.1194e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Программируемые постоянные запаминающие устройства(ППЗУ)', '0.1194e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Перепрограммируемые постоянные запаминающие устройства(РПЗУ)', '0.1021e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Микросхемы интегральные полупроводниковые аналоговые', '0.1488e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Микросхемы интегральные гибридные', '0.0727e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды кремниевые(выпрямительные)', '0.0148e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды кремниевые(импульсные)', '0.0034e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды кремниевые(столбы выпрямительные)', '0.0225e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды кремниевые(варикапы подстроечные)', '0.0030e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды кремниевые(диодные сборки)', '0.0011e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды кремниевые(стабилитроны)', '0.0010e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы биполярные кремниевые', '0.0114e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы полевые(кремниевые)', '0.0190e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы полевые(арсенидогаллиевые)', '0.1159e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторные сборки', '0.0313e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы кремниевые', '0.0300e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Генераторы шума', '0.0230e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Ограничители напряжения', '0.0010e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ смесительные(кремниевые)', '0.0205e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ смесительные(арсенидогаллиевые)', '0.0470e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ детокторные(кремниевые)', '0.1024e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ детокторные(арсенидогаллиевые)', '0.0924e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ параметрические', '0.0437e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ арсенидогаллиевые переключательные(кремниевые)', '0.0403e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ арсенидогаллиевые переключательные(арсенидогаллиевые)', '0.0622e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ арсенидогаллиевые ограничительные(кремниевые)', '0.0403e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ арсенидогаллиевые ограничительные(арсенидогаллиевые)', '0.0622e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ умножительные(кремниевые)', '0.3624e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ умножительные(арсенидогаллиевые)', '0.0655e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ настроечные(кремниевые)', '0.3624e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ настроечные(арсенидогаллиевые)', '0.0655e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ генераторные(кремниевые)', '0.0313e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Диоды СВЧ генераторные(арсенидогаллиевые)', '0.0353e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ биполярные(малой мощности)', '0.0186e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ биполярные(средней мощности)', '0.0186e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ биполярные большой мощности(для метализации на основе алюминия)', '0.2400e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ биполярные большой мощности(для метализации на основе золота)', '0.0440e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ кремниевые(малой мощности)', '0.0186e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ кремниевые(средней мощности)', '0.0186e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ кремниевые большой мощности(для метализации на основе алюминия)', '0.2400e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторы СВЧ кремниевые большой мощности(для метализации на основе золота)', '0.0440e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Транзисторные сборки СВЧ', '0.0056e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фотодиоды (неохлождаемые на кремния)', '0.281e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фотодиоды (неохлождаемые на германия)', '0.927e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фотодиоды (неохлождаемые на InGaAsP)', '1.728e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фотодиоды (неохлождаемые на InSb)', '15.8e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фоторезисторы (неохлождаемые на PbS)', '1.8e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фоторезисторы (неохлождаемые на InSb)', '78.0e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фоторезисторы (неохлождаемые на CdHgTe)', '7.2e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Фоторезисторы (неохлождаемые на PbSe)', '90.20e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные непроволочные(металлодиэлектрические не прецизионные)', '0.0280e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные непроволочные(металлодиэлектрические прецизионные)', '0.0216e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные непроволочные(металлизированные)', '0.0200e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные непроволочные(композиционные пленочные)', '0.0145e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные непроволочные(композиционные объемные)', '0.0218e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные проволочные(нагрузочные)', '0.0084e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные проволочные(прецизионные)', '0.0026e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные проволочные(особостабильные)', '0.0067e-10', '1/ч');
insert into refusal(element, lambda, unit) VALUES ('Резисторы постоянные проволочные(фольговые)', '0.0077e-10', '1/ч');
